<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-02T15:23:10 IST" name="Default suite" finished-at="2023-11-02T15:23:23 IST" duration-ms="12439">
    <groups>
    </groups>
    <test started-at="2023-11-02T15:23:10 IST" name="Default test" finished-at="2023-11-02T15:23:23 IST" duration-ms="12439">
      <class name="api.Test.UserTest2">
        <test-method is-config="true" signature="SetUp()[pri:0, instance:api.Test.UserTest2@3f191845]" started-at="2023-11-02T15:23:11 IST" name="SetUp" finished-at="2023-11-02T15:23:12 IST" duration-ms="1482" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="Test_postUser()[pri:1, instance:api.Test.UserTest2@3f191845]" started-at="2023-11-02T15:23:12 IST" name="Test_postUser" finished-at="2023-11-02T15:23:17 IST" duration-ms="4957" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Test_postUser -->
        <test-method signature="GetUser_test()[pri:2, instance:api.Test.UserTest2@3f191845]" started-at="2023-11-02T15:23:17 IST" name="GetUser_test" finished-at="2023-11-02T15:23:19 IST" duration-ms="1245" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [204] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [204] but found [200]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at org.testng.Assert.assertEquals(Assert.java:1274)
at api.Test.UserTest2.GetUser_test(UserTest2.java:61)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GetUser_test -->
        <test-method signature="UpdateUser_test()[pri:3, instance:api.Test.UserTest2@3f191845]" started-at="2023-11-02T15:23:19 IST" name="UpdateUser_test" finished-at="2023-11-02T15:23:21 IST" duration-ms="2610" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UpdateUser_test -->
        <test-method signature="DeleteUser_test()[pri:4, instance:api.Test.UserTest2@3f191845]" started-at="2023-11-02T15:23:21 IST" name="DeleteUser_test" finished-at="2023-11-02T15:23:23 IST" duration-ms="1368" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DeleteUser_test -->
      </class> <!-- api.Test.UserTest2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
